# Generated by Django 4.2 on 2023-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0004_userdetails_phone_userdetails_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Please select a drink type'), ('A', 'Americano'), ('C', 'Cappuccino'), ('CD', 'Cold Brew Coffee')], max_length=10)),
                ('size', models.CharField(choices=[(None, 'Please select a size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
    ]
